<?php
function get_emojis_with_labels(): array {
    return [
        'faces' => [
            ['😀', 'grinning face'],
            ['😃', 'grinning face with big eyes'],
            ['😄', 'grinning face with smiling eyes'],
            ['😁', 'beaming face with smiling eyes'],
            ['😆', 'grinning squinting face'],
            ['😅', 'grinning face with sweat'],
            ['😂', 'face with tears of joy'],
            ['🤣', 'rolling on the floor laughing'],
            ['😊', 'smiling face with smiling eyes'],
            ['😇', 'smiling face with halo'],
            ['🙂', 'slightly smiling face'],
            ['🙃', 'upside-down face'],
            ['😉', 'winking face'],
            ['😌', 'relieved face'],
            ['😍', 'smiling face with heart-eyes'],
            ['🥰', 'smiling face with hearts'],
            ['😘', 'face blowing a kiss'],
            ['😗', 'kissing face'],
            ['😚', 'kissing face with closed eyes'],
            ['😋', 'face savoring food'],
            ['😛', 'face with tongue'],
            ['😜', 'winking face with tongue'],
            ['😝', 'squinting face with tongue'],
            ['🤪', 'zany face'],
            ['🤨', 'face with raised eyebrow'],
        ],
        'gestures' => [
            ['👋', 'waving hand'],
            ['🤚', 'raised back of hand'],
            ['🖐️', 'hand with fingers splayed'],
            ['✋', 'raised hand'],
            ['🖖', 'vulcan salute'],
            ['👌', 'OK hand'],
            ['🤌', 'pinched fingers'],
            ['🤏', 'pinching hand'],
            ['✌️', 'victory hand'],
            ['🤞', 'crossed fingers'],
            ['🤟', 'love-you gesture'],
            ['🤘', 'sign of the horns'],
            ['🤙', 'call me hand'],
            ['👈', 'backhand index pointing left'],
            ['👉', 'backhand index pointing right'],
            ['👆', 'backhand index pointing up'],
            ['🖕', 'middle finger'],
            ['👇', 'backhand index pointing down'],
            ['☝️', 'index pointing up'],
            ['👍', 'thumbs up'],
            ['👎', 'thumbs down'],
            ['✊', 'raised fist'],
            ['👊', 'oncoming fist'],
            ['🤛', 'left-facing fist'],
            ['🤜', 'right-facing fist'],
        ],
        'nature' => [
            ['☀️', 'sun'],
            ['🌤️', 'sun behind small cloud'],
            ['⛅', 'sun behind cloud'],
            ['🌥️', 'sun behind large cloud'],
            ['🌦️', 'sun behind rain cloud'],
            ['🌧️', 'cloud with rain'],
            ['🌨️', 'cloud with snow'],
            ['❄️', 'snowflake'],
            ['🌩️', 'cloud with lightning'],
            ['🌪️', 'tornado'],
            ['🌈', 'rainbow'],
            ['🔥', 'fire'],
            ['💧', 'droplet'],
            ['🌊', 'water wave'],
            ['🌫️', 'fog'],
            ['🌬️', 'wind face'],
            ['🍃', 'leaf fluttering in wind'],
            ['🍂', 'fallen leaf'],
            ['🍁', 'maple leaf'],
            ['🌾', 'sheaf of rice'],
            ['🌵', 'cactus'],
            ['🌴', 'palm tree'],
            ['🌳', 'deciduous tree'],
            ['🌲', 'evergreen tree'],
            ['🌸', 'cherry blossom'],
        ],
        'animals' => [
            ['🐶', 'dog face'],
            ['🐱', 'cat face'],
            ['🐭', 'mouse face'],
            ['🐹', 'hamster face'],
            ['🐰', 'rabbit face'],
            ['🦊', 'fox face'],
            ['🐻', 'bear face'],
            ['🐼', 'panda face'],
            ['🐨', 'koala'],
            ['🐯', 'tiger face'],
            ['🦁', 'lion face'],
            ['🐮', 'cow face'],
            ['🐷', 'pig face'],
            ['🐸', 'frog face'],
            ['🐵', 'monkey face'],
            ['🙈', 'see-no-evil monkey'],
            ['🙉', 'hear-no-evil monkey'],
            ['🙊', 'speak-no-evil monkey'],
            ['🐔', 'chicken'],
            ['🐧', 'penguin'],
            ['🐦', 'bird'],
            ['🐤', 'baby chick'],
            ['🐣', 'hatching chick'],
            ['🐺', 'wolf face'],
            ['🦄', 'unicorn face'],
        ],
        'people' => [
            ['🧑', 'person'],
            ['👩', 'woman'],
            ['👨', 'man'],
            ['👶', 'baby'],
            ['👧', 'girl'],
            ['👦', 'boy'],
            ['🧒', 'child'],
            ['👵', 'older woman'],
            ['👴', 'older man'],
            ['🧓', 'older adult'],
            ['👲', 'person with skullcap'],
            ['🧕', 'woman with headscarf'],
            ['👳', 'person wearing turban'],
            ['👮', 'police officer'],
            ['🕵️', 'detective'],
            ['👷', 'construction worker'],
            ['💂', 'guard'],
            ['👸', 'princess'],
            ['🤴', 'prince'],
            ['🦸', 'superhero'],
            ['🦹', 'supervillain'],
            ['🧙', 'mage'],
            ['🧛', 'vampire'],
            ['🧟', 'zombie'],
            ['🧞', 'genie'],
        ],
        'emotions' => [
            ['❤️', 'red heart'],
            ['🧡', 'orange heart'],
            ['💛', 'yellow heart'],
            ['💚', 'green heart'],
            ['💙', 'blue heart'],
            ['💜', 'purple heart'],
            ['🖤', 'black heart'],
            ['🤍', 'white heart'],
            ['🤎', 'brown heart'],
            ['💖', 'sparkling heart'],
            ['💗', 'growing heart'],
            ['💓', 'beating heart'],
            ['💞', 'revolving hearts'],
            ['💕', 'two hearts'],
            ['💘', 'heart with arrow'],
            ['💝', 'heart with ribbon'],
            ['💔', 'broken heart'],
            ['❣️', 'heart exclamation'],
            ['💟', 'heart decoration'],
            ['💤', 'zzz'],
            ['🤯', 'exploding head'],
            ['😱', 'face screaming in fear'],
            ['🥵', 'hot face'],
            ['🥶', 'cold face'],
            ['🤬', 'face with symbols on mouth'],
        ],
        'activities' => [
            ['🚴', 'person biking'],
            ['🚵', 'person mountain biking'],
            ['🏃', 'person running'],
            ['🏃‍♀️', 'woman running'],
            ['🏋️', 'person lifting weights'],
            ['🏊', 'person swimming'],
            ['🏄', 'person surfing'],
            ['🚣', 'person rowing boat'],
            ['🤽', 'person playing water polo'],
            ['🤾', 'person playing handball'],
            ['⛹️', 'person bouncing ball'],
            ['🤸', 'person cartwheeling'],
            ['🧘', 'person in lotus position'],
            ['🏇', 'horse racing'],
            ['🧗', 'person climbing'],
            ['🏕️', 'camping'],
            ['🎣', 'fishing pole'],
            ['⛺', 'tent'],
            ['🎿', 'skis'],
            ['🏂', 'snowboarder'],
            ['🛹', 'skateboard'],
            ['🛼', 'roller skate'],
            ['🧺', 'basket'],
            ['🎯', 'bullseye'],
            ['🏌️', 'person golfing'],
        ],
        'hobbies' => [
            ['📚', 'books'],
            ['📖', 'open book'],
            ['🎧', 'headphone'],
            ['🎵', 'musical note'],
            ['🎶', 'musical notes'],
            ['🎤', 'microphone'],
            ['🎼', 'musical score'],
            ['🎷', 'saxophone'],
            ['🎸', 'guitar'],
            ['🎹', 'musical keyboard'],
            ['🎺', 'trumpet'],
            ['🎻', 'violin'],
            ['🪕', 'banjo'],
            ['✍️', 'writing hand'],
            ['🖊️', 'pen'],
            ['📝', 'memo'],
            ['📷', 'camera'],
            ['📸', 'camera with flash'],
            ['🎨', 'artist palette'],
            ['🧵', 'thread'],
            ['🧶', 'yarn'],
            ['🪡', 'sewing needle'],
            ['📹', 'video camera'],
            ['🎬', 'clapper board'],
            ['🧩', 'puzzle piece'],
        ],
        'tech' => [
            ['💻', 'laptop'],
            ['🖥️', 'desktop computer'],
            ['🖨️', 'printer'],
            ['🖱️', 'computer mouse'],
            ['⌨️', 'keyboard'],
            ['📱', 'mobile phone'],
            ['📲', 'mobile phone with arrow'],
            ['📞', 'telephone receiver'],
            ['☎️', 'telephone'],
            ['📟', 'pager'],
            ['📠', 'fax machine'],
            ['🔋', 'battery'],
            ['🔌', 'electric plug'],
            ['💽', 'computer disk'],
            ['💾', 'floppy disk'],
            ['💿', 'optical disk'],
            ['📀', 'dvd'],
            ['🧮', 'abacus'],
            ['🕹️', 'joystick'],
            ['📡', 'satellite antenna'],
            ['🔍', 'magnifying glass tilted left'],
            ['🔎', 'magnifying glass tilted right'],
            ['🧭', 'compass'],
            ['📊', 'bar chart'],
            ['📈', 'chart increasing'],
        ],
        'travel' => [
            ['✈️', 'airplane'],
            ['🛫', 'airplane departure'],
            ['🛬', 'airplane arrival'],
            ['🚗', 'automobile'],
            ['🚕', 'taxi'],
            ['🚙', 'sport utility vehicle'],
            ['🚌', 'bus'],
            ['🚎', 'trolleybus'],
            ['🏎️', 'racing car'],
            ['🚓', 'police car'],
            ['🚑', 'ambulance'],
            ['🚒', 'fire engine'],
            ['🚐', 'minibus'],
            ['🛻', 'pickup truck'],
            ['🚚', 'delivery truck'],
            ['🚛', 'articulated lorry'],
            ['🚜', 'tractor'],
            ['🚲', 'bicycle'],
            ['🛴', 'kick scooter'],
            ['🚨', 'police car light'],
            ['⛵', 'sailboat'],
            ['🚤', 'speedboat'],
            ['🛳️', 'passenger ship'],
            ['⛴️', 'ferry'],
            ['🚁', 'helicopter'],
        ],
        'food' => [
            ['🍎', 'red apple'],
            ['🍌', 'banana'],
            ['🍇', 'grapes'],
            ['🍓', 'strawberry'],
            ['🍉', 'watermelon'],
            ['🍍', 'pineapple'],
            ['🥭', 'mango'],
            ['🍑', 'peach'],
            ['🍒', 'cherries'],
            ['🍅', 'tomato'],
            ['🥦', 'broccoli'],
            ['🥕', 'carrot'],
            ['🌽', 'ear of corn'],
            ['🥔', 'potato'],
            ['🍞', 'bread'],
            ['🥐', 'croissant'],
            ['🥖', 'baguette bread'],
            ['🧀', 'cheese wedge'],
            ['🍕', 'pizza'],
            ['🍔', 'hamburger'],
            ['🍟', 'french fries'],
            ['🌭', 'hot dog'],
            ['🥪', 'sandwich'],
            ['🌮', 'taco'],
            ['🍣', 'sushi'],
        ],

        //'custom' => get_user_emojis($db),
    ];
}
