services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./configs/nginx/folder.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.2-fpm-alpine
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    command: >
      sh -c "
      chown -R www-data:www-data /var/www/html/storage &&
      chmod -R 775 /var/www/html/storage &&
      php-fpm
      "
    restart: unless-stopped

volumes:
  src:
    driver: local