name: Build and publish artifacts
run-name: ${{ gitea.repository }} build and publish
on:
  push:
    tags:
      - v*.**.**

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build archive
        run: |
          tar \
            --transform 's,^,tkr/,' \
            --exclude='storage/db' \
            --exclude='storage/ticks' \
            --exclude='storage/upload' \
            -czvf tkr.${{ gitea.ref_name }}.tgz \
            config public src storage templates
      - name: Push to Generic gitea registry
        run: |
          curl \
            --user ${{ secrets.CONTAINER_REGISTRY_USERNAME}}:${{ secrets.CONTAINER_REGISTRY_TOKEN }} \
            --upload-file tkr.${{ gitea.ref_name}}.tgz \
            https://gitea.subcultureofone.org/api/packages/${{ secrets.CONTAINER_REGISTRY_USERNAME }}/generic/tkr/${{ gitea.ref_name }}/tkr.${{ gitea.ref_name }}.tgz
