services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./tkr-nginx-folder.conf:/etc/nginx/conf.d/default.conf
            - ./../../tkr:/tkr
    php:
        image: php:fpm
        volumes:
            - ./../../tkr:/tkr